---
title: "Predicting Housing Code Violations"
author: "Maxwell Austensen"
date: '`r Sys.Date()`'
output:
  github_document:
    toc: yes
    toc_depth: 3
  html_notebook: default
---

Overview
--------

The purpose of this project is to to predict serious housing code violations in multi-family rental building in New York City. All data is taken from publicly available sources, and is organized at the borough-block-lot (BBL) level. The plan is to use all data available in 2015 to predict violations in 2016. 


Repository Organization
------------------------

Directory              | Description
-----------------------|------------------------------------------------------------------------------------------------
`./`                   | Pseudo makefiles for data and analysis/maps
`./analysis`           | R Notebook files for main analysis
`./violations-app`     | [`shiny`](https://shiny.rstudio.com/) files for [app to visualize model predictions](https://maxwell-austensen.shinyapps.io/violations-app/?_inputs_&cd=%22East%20Flatbush%22&map_bounds=%7B%22north%22%3A40.656078261538%2C%22east%22%3A-73.9363574981689%2C%22south%22%3A40.6448451375211%2C%22west%22%3A-73.9578795433044%7D&map_center=%7B%22lng%22%3A-73.9471185207367%2C%22lat%22%3A40.6504619359014%7D&map_shape_mouseout=%7B%22id%22%3Anull%2C%22.nonce%22%3A0.643297732837%2C%22lat%22%3A40.6542713213941%2C%22lng%22%3A-73.9562702178955%7D&map_shape_mouseover=%7B%22id%22%3Anull%2C%22.nonce%22%3A0.525286392328233%2C%22lat%22%3A40.6543364372042%2C%22lng%22%3A-73.9559268951416%7D&map_zoom=16&model=%22Random%20Forest%20Predictions%22&tbl_cell_clicked=%7B%22row%22%3A3%2C%22col%22%3A1%2C%22value%22%3A%223050840061%22%7D&tbl_row_last_clicked=3&tbl_rows_current=%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D&tbl_rows_selected=3&tbl_search=%22%22&tbl_state=null)
`./maps`               | R scripts to create maps and final map images
`./munge`              | R scripts to download raw files, clean data, and prep for joining all sources
`./data-raw`           | Raw data files, and cleaned individual data sets, including crosswalks _(git-ignored due to file size)_
`./data-documentation` | Documentation files downloaded for data sources
`./data`               | Final cleaned and joined data sets _(only samples of data are not git-ignored)_
`./functions`          | R functions used throughout project
`./presentations`      | Slide presentations for class using [`xaringan`](https://github.com/yihui/xaringan)
`./packrat`            | Files for [`packrat`](https://rstudio.github.io/packrat/) R package management system _(do not edit)_


Reproducability Instructions
----------------------------

1. Clone repo and open the RStudio project file `edsp17proj-austensen.Rproj`
    * The package `packrat` will be automatically installed from source files in the repository. Then all the other packages used in this project will be installed from instructions saved in this repo. All installed packages will be saved in the packrat sub-directories of this repo. This allows you to easily get all the packages you need to reproduce this project while not disrupting your own local package library (eg. change versions).
2. Run `source("make_data.R")` to download and prepare all the data necessary to reproduce all the analysis.
3. Run `source("make_analysis_maps.R")` to run all the analysis scripts, rendering .nb.html files and generating map images.


To-Do
-----

* Improve logit model using `MASS::stepAIC()` to choose a model

* Plot decision tree (look at `rpart.plot` package)

* Consider changing from classification to regression using adjusted serious violations count

* Deal with missing data problems
    * Impute missing data
      * simple mean imputation, 
      * mean by zip code and/or building type, 
      * should also see if missing-not-at-random
      * look for values in past years of data (older pluto/rpad versions), 
      * regressions using other variables
    
* Add to evaluation of models using tests recommended in Dietrich (1997) reading
  
  
### Data source wish-list

* [Building permits (DOB)](https://data.cityofnewyork.us/Housing-Development/DOB-Job-Application-Filings/ic3t-wcy2)
* [Oil Boilers](https://data.cityofnewyork.us/Housing-Development/Oil-Boilers-Detailed-Fuel-Consumption-and-Building/jfzu-yy6n)
* [Rodent Inspection](https://data.cityofnewyork.us/Health/Rodent-Inspection/p937-wjvj)
* [Subsidized Housing Database](http://app.coredata.nyc/)
* [Likely Rent-Regulated Units](http://taxbills.nyc/)
* Certificates of Occupancy (DCP - FOIL)
* Open Balance File (Property Tax Delinquency) (DOF - FOIL)
* HPD registration files - corporate owner
* DOF sales data - price and date of last sale
* Tract-level ACS - median rent, poverty rate, etc.
* SBA-level HVS - building quality, pests, etc. 

