---
title: "Predicting Housing Code Violations"
subtitle: "Introduction Presentation"
author: "Maxwell Austensen"
date: "2017-01-30"
output:
  xaringan::moon_reader:
    css: ["default", "my-theme.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

class: left, top

### What are you trying to do?

--

Predict serious housing code violations in NYC

--

### Who cares?

--

__New Yorkers living in rental housing__
* Prediction could help to reduce the frequency/severity of violations
  
--

__NYC Department of Housing Preservation and Development (HPD)__
* Prediction could improve efficient/effective use limited resources

--

__Non-Governmental Organizations (eg. [Heat Seek](http://heatseek.org/), [JustFix.nyc](http://www.justfix.nyc/))__
* Prediction could improve targeting of resources for outreach

---
class: left, top

### What will success look like?

--

Sufficiently accurate predictions to be helpful to HPD and/or community organizations

--

Include estimated likelihood of violations to allow targeting resources

--

Interpretable model to provide some understanding strongest predictors

--

Effective measures taken to minimize potential biases in models
  * eg. Communities less likely to report violations 

--

### What impact will it have?

--

Preemptive HPD inspections could prevent violations or reduce their severity or duration

--

Better targeting for outreach could allow organizations to serve more residents

---
class: left, top

### What will the data look like? 

--

Building level data on all multi-family rental buildings, including as many of the following data sources as time permits:
* Complaints, emergency repairs, litigation, and violations .small[(HPD open data)]
* Local rent levels/changes .small[(Craigslist)]
* Tax delinquencies .small[(DOF FOIL request)]
* Average neighborhood housing quality .small[(NYC Housing & Vacancy Survey)]
* Subsidized properties .small[(NYU Furman Center)]

--

### What approach will you take? 

--

  1. Quickly compile a minimal version of the necessary data set
  2. Test different models with simple set of inputs
  3. Add more data from other sources after some viable models built

--

### What skills will you need?

--

Will need to learn about classification algorithms 


---
class: inverse, center, middle

# Thanks!

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).

